# Generated by Django 2.0 on 2018-09-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=140, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price')),
            ],
        ),
    ]
