# Generated by Django 2.0 on 2018-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credential',
            field=models.CharField(blank=True, choices=[('M', 'Manager'), ('ADMIN', 'ADMIN')], max_length=30, null=True, verbose_name='Credential'),
        ),
    ]
